.PHONY: up down logs test test-integration test-e2e lint backend frontend dev stop db-reset db-add-is-competitor seed-offline clean db-upgrade db-downgrade db-current db-revision db-history db-stamp-head

# ── Docker Compose ──────────────────────────────────────────────

## Start the full stack (backend + frontend + database) via Docker Compose
up:
	docker compose up --build -d

## Stop the full stack
down:
	docker compose down

## Show logs from all containers (follow mode)
logs:
	docker compose logs -f

# ── Local development (without Docker) ─────────────────────────

## Start backend server locally
backend:
	cd backend && python -m uvicorn app.main:app --reload --port 8000

## Start frontend dev server locally
frontend:
	cd frontend && npm run dev

## Start both backend and frontend locally (Windows)
## Backend runs in background. If you get "network error" on login, run "make backend" in another terminal to see backend logs (e.g. DB not running).
dev:
	@echo Starting backend on http://localhost:8000 ...
	cmd /C "cd /d $(CURDIR)\backend && start /B python -m uvicorn app.main:app --reload --port 8000"
	@echo Starting frontend on http://localhost:3000 ...
	cd frontend && npm run dev

## Stop local backend and frontend processes
stop:
	@echo Stopping Python/uvicorn processes...
	-taskkill /F /IM python.exe 2>nul || pkill -f uvicorn 2>/dev/null || true
	@echo Stopping Node/Next.js processes...
	-taskkill /F /IM node.exe 2>nul || pkill -f next 2>/dev/null || true
	@echo Done.

# ── Testing & quality ──────────────────────────────────────────

## Run backend unit tests
test:
	cd backend && python -m pytest tests/ -v --ignore=tests/e2e --ignore=tests/integration

## Run integration tests (uses in-memory SQLite, no running server needed)
test-integration:
	cd backend && python -m pytest tests/integration/ -v

## Run end-to-end tests (requires running backend via make up)
test-e2e:
	cd backend && python -m pytest tests/e2e/ -v

## Run linters
lint:
	cd backend && python -m py_compile app/main.py
	cd frontend && npm run lint

# ── Database ───────────────────────────────────────────────────

## Apply all pending Alembic migrations (run after `make up`)
db-upgrade:
	docker compose exec backend alembic upgrade head

## Roll back one migration revision
db-downgrade:
	docker compose exec backend alembic downgrade -1

## Show current Alembic revision
db-current:
	docker compose exec backend alembic current

## Create a new autogenerated migration (usage: make db-revision msg="add column foo")
db-revision:
	docker compose exec backend alembic revision --autogenerate -m "$(msg)"

## Show migration history
db-history:
	docker compose exec backend alembic history --verbose

## Stamp DB as up-to-date without running migrations (one-time: existing DB from create_all era)
## Example: docker compose exec backend alembic stamp head
db-stamp-head:
	docker compose exec backend alembic stamp head

## Reset database (drops all tables and Alembic version — use only as escape hatch)
## After reset, run: make db-upgrade
## For standalone DB container (review-insight-db), run: docker exec -i review-insight-db psql -U postgres -d review_insight -c "DROP TABLE IF EXISTS alembic_version, competitor_links, analyses, reviews, businesses, users CASCADE;"
db-reset:
	docker compose exec -T db psql -U postgres -d review_insight \
		-c "DROP TABLE IF EXISTS alembic_version, competitor_links, analyses, reviews, businesses, users CASCADE;"
	@echo Tables dropped. Run: make db-upgrade

## Add is_competitor column to existing DB (legacy escape hatch; prefer migrations)
db-add-is-competitor:
	docker compose exec -T db psql -U postgres -d review_insight \
		-c "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS is_competitor boolean NOT NULL DEFAULT false;"
	@echo Column added. Restart backend if needed.

# ── Offline demo data ─────────────────────────────────────────

## Seed database with offline demo businesses and competitor links
seed-offline:
	docker compose exec backend python -m scripts.seed_offline

# ── Cleanup ────────────────────────────────────────────────────

## Remove local build artifacts and caches
clean:
	-rmdir /S /Q backend\__pycache__ 2>nul || rm -rf backend/__pycache__
	-rmdir /S /Q backend\.pytest_cache 2>nul || rm -rf backend/.pytest_cache
	-rmdir /S /Q frontend\.next 2>nul || rm -rf frontend/.next
	@echo Cleaned.
