"""add businesses notes column

Revision ID: e273fafbe8de
Revises: 96daf85753e5
Create Date: 2026-03-20 10:37:37.990622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e273fafbe8de"
down_revision: Union[str, Sequence[str], None] = "96daf85753e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "notes")
    # ### end Alembic commands ###
